configVersion: 5
logFile: "/plugins/LoggerX/events.log"
archiveOldLogs: true
archiveLocation: "/plugins/LoggerX/archive"
logLoggerStatus: true
logBlockBreak: true
logBlockPlace: true
logPlayerDeath: true
logPlayerJoin: true
logPlayerQuit: true
logItemDrop: true
logBucketFill: true
logBucketEmpty: true
logPlayerCommand: true
logFire: true
logContainerOpen: true
logItemFrameDrop: true
