configVersion: 2
logFile: "/logs/events.log"
logLoggerStatus: true
logBlockBreak: true
logBlockPlace: true
logPlayerDeath: true
logPlayerJoin: true
logPlayerQuit: true
logItemDrop: true
logBucketFill: true
logBucketEmpty: true
logPlayerCommand: true
logFire: true
logChestOpen: true
